# Generated by Django 5.1.7 on 2025-03-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
