# Generated by Django 5.1.7 on 2025-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
