# Generated by Django 5.1.7 on 2025-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_booking_capacity_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
