# Generated by Django 5.1.7 on 2025-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
